In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
import scipy.stats as ss

In [2]:
df = pd.read_csv("T7-7.dat", header=None, names=['Y1','Y2','Y3','Y4','Z1','Z2','Z3','Z4'], sep='\t')
df.head()

Y1     Y2     Y3     Y4     Z1      Z2      Z3     Z4
0  21.312  7.039  5.326  0.932 -0.030  35.239  36.991  1.057
1  21.206  6.979  5.237  0.871  0.015  35.713  36.851  1.064
2  20.709  6.779  5.060  0.742  0.025  39.220  30.586  1.053
3  19.542  6.601  4.479  0.513  0.030  39.756  21.072  1.050
4  20.449  6.795  4.912  0.577 -0.070  32.991  36.570  1.049

In [3]:
X = df[['Z1','Z2','Z3','Z4']]
y = df[['Y1','Y2','Y3','Y4']]

In [4]:
X.shape, y.shape

((62, 4), (62, 4))

In [5]:
reg = LinearRegression().fit(X, y)
coefficients = reg.coef_
intercepts = reg.intercept_
coefficients.shape, intercepts.shape

/usr/local/lib/python3.7/site-packages/sklearn/linear_model/base.py:485: RuntimeWarning: internal gelsd driver lwork query error, required iwork dimension not returned. This is likely the result of LAPACK bug 0038, fixed in LAPACK 3.2.2 (released July 21, 2010). Falling back to 'gelss' driver.
  linalg.lstsq(X, y)


((4, 4), (4,))

In [6]:
np.set_printoptions(suppress=True)
np.round(coefficients,2)

array([[-3.12,  0.1 ,  0.05, 85.08],
       [-1.18,  0.01,  0.01, 28.75],
       [-1.49,  0.05,  0.03, 45.8 ],
       [-0.55,  0.03,  0.01, 16.22]])

In [7]:

np.round(intercepts,2)

array([-74.23, -24.01, -45.76, -17.73])

In [8]:
est = np.matmul(X, coefficients.T) + intercepts
est.shape

(62, 4)

In [9]:
cov = np.cov(X.T)
mu = np.mean(X)

cov.shape, mu.shape

((4, 4), (4,))

In [10]:
N = len(X)
mean = np.mean(X)
total=np.zeros(shape=[4,4])
for i in range(N):
    sample = X.iloc[i] - mean
    total+=np.outer(sample, sample.T)
print(total/N)

[[   0.06126434    3.30561305   -3.16220473    0.00567822]
 [   3.30561305  217.48626109 -182.64292413    0.34198874]
 [  -3.16220473 -182.64292413  303.42569983   -0.39977974]
 [   0.00567822    0.34198874   -0.39977974    0.00085574]]


In [11]:
X24 = df[['Z2','Z4']]
reg24 = LinearRegression().fit(X24, y)
coefficients24 = reg24.coef_
intercepts24 = reg24.intercept_
X24.shape, coefficients24.shape, intercepts24.shape

((62, 2), (4, 2), (4,))

In [12]:
est24 = np.matmul(X24, coefficients24.T) + intercepts24
est24.shape

(62, 4)

In [13]:
from sklearn.metrics import mean_squared_error as mean_error

In [19]:
F = mean_error(y, est)

In [20]:
R = mean_error(y, est24)

In [21]:
((R-F)/2)/(R/57)

5.165209877403232

In [26]:
R,F

(0.814735206836393, 0.6670763177900947)

In [24]:
def Ftest_pvalue(d1,d2):
    """docstring for Ftest_pvalue"""
    df1 = len(d1) - 1
    df2 = len(d2) - 1
    F = np.var(d1) / np.var(d2)
    print("F",F)
    single_tailed_pval = ss.f.cdf(F,df1,df2)
#     double_tailed_pval = single_tailed_pval * 2
    print("P", 1-single_tailed_pval)
#     return F, 1-single_tailed_pval

In [25]:
Ftest_pvalue(est, est24)

F 1.0023830909550033
P 0.496306972276815
